# Generated by Django 5.0.3 on 2024-03-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iro', models.CharField(max_length=200, verbose_name='色')),
            ],
        ),
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('vocab', models.CharField(max_length=200, verbose_name='英単語')),
                ('mean', models.CharField(max_length=200, verbose_name='意味')),
                ('cata', models.CharField(choices=[('verb', '動詞'), ('nouns', '名詞'), ('adjective', '形容詞'), ('adverb', '副詞'), ('others', 'その他'), ('phrase', '熟語')], max_length=200, verbose_name='品詞')),
            ],
        ),
    ]
