# Generated by Django 5.0.3 on 2024-03-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_alter_wordlist_cata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='cata',
            field=models.CharField(choices=[('動詞', 'verb'), ('名詞', 'nouns'), ('形容詞', 'adjective'), ('副詞', 'adverb'), ('その他', 'others'), ('熟語', 'phrase')], max_length=100, verbose_name='品詞'),
        ),
    ]
