# Generated by Django 5.0.3 on 2024-03-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_alter_wordlist_cata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='cata',
            field=models.CharField(choices=[('動詞', '動詞'), ('名詞', '名詞'), ('形容詞', '形容詞'), ('副詞', '副詞'), ('その他', 'その他'), ('熟語', '熟語')], max_length=100, verbose_name='品詞'),
        ),
    ]
