# Generated by Django 5.0.3 on 2024-03-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_alter_wordlist_cata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wordlist',
            new_name='WordlistE',
        ),
    ]
